language: java
script: mvn test
after_success:
  - mvn clean test jacoco:report coveralls:report
jdk:
  - oraclejdk8
before_install:  
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
